using BannerKings;
using BannerKings.CampaignContent.Traits;
using BannerKings.Managers.Education.Books;
using BannerKings.Managers.Education.Languages;
using BannerKings.Managers.Innovations.Eras;
using BannerKings.Managers.Items;
using BannerKings.Managers.Skills;
using BKCEKPatch.Languages;
using HarmonyLib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.Core;
using TaleWorlds.Localization;

namespace BKROTPatch.Patches
{
    [HarmonyPatch(typeof(DefaultBookTypes), "Initialize")]
    internal class DefaultBookTypesInitializePatch
    {
        public static bool Prefix(DefaultBookTypes __instance)
        {
            __instance.SkullsEleftheroi.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookSkullsEleftheroi, new TextObject("Subtitled “slaves, servants, soldiers”, this book styles itself as a scientific study of the skull shapes and sizes of the Naathi. Its anonymous author claims that the form of the skulls shows that they are perfect “human livestock”. He argues that runaway slaves have lost all rights and the fact that they return to Valyrian lands only to enlist as servants and soldiers is proof that they are less than human. As a biological study, its methods of measuring body parts and collecting data has some limited merits.", null), ROTLanguages.Instance.LowValyrian, BookUse.Focusbook, DefaultSkills.Medicine, null);
            __instance.WestGemynt.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookWestGemynt, new TextObject("Documented interviews with the last surviving immigrants from north of the Wall. The book is millennia old and has become a major source for both romantic tales and academic debate. Yet, for many of the current Northmen, as generations have been entirely born within The Seven Kingdoms, their homeland has since become a distant memory, a myth.", null), ROTLanguages.Instance.OldTongue, BookUse.Focusbook, BKSkills.Instance.Scholarship, null);
            __instance.FabulaeAquilae.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookFabulaeAquilae, new TextObject("Collected by several great theologians, poets and even Citadel maesters - “tales of the Dragon”, or “the books of tales” as it is colloquially called has become the standard popular versions of old folklore. Nearly all the stories are historical allegories or degraded myths of the gods of Valyria and other deities on their shapeshifting adventures as eagle, wolf or dragon. For the descendants of Valyria, these tales are their history, faith and nation.", null), ROTLanguages.Instance.HighValyrian, BookUse.Focusbook, BKSkills.Instance.Theology, null);
            __instance.NakedFingers.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookNakedFingers, new TextObject("Written in prison by a former boss and informant in the Brotherhood Without Banners, the book claims to expose tactics and methods of the Brotherhood Without Banners. It also exposes many of the weaknesses in the Westerosi justice system.", null), ROTLanguages.Instance.Westerosi, BookUse.Focusbook, DefaultSkills.Roguery, null);
            __instance.IrkBitig.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookIrkBitig, new TextObject("The Book of Visions is a collection of tales from the Dothraki peoples, written down in poetic form. The book describes various small stories that serve to depict omens, be them beningn or not. The poems provide invaluable insight into the Dothraki culture and theology.", null), ROTLanguages.Instance.Dothraki, BookUse.Focusbook, BKSkills.Instance.Theology, null);
            __instance.GardenArgument.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookGardenArgument, new TextObject("A comedic Braavosi story that criticizes the conventions of courtly love. A lover steals into a garden in Lys, and plies her with lots of witty lines to persuade his lover to submit to his embraces. She shoots down all of his advances one by one, them when he is downcast, she takes him in her arms and tell him that she wanted him all along, except on her terms, not his. “All the silks of Yi Ti, all the furs of Ib...”", null), ROTLanguages.Instance.LowValyrian, BookUse.Skillbook, DefaultSkills.Charm, DefaultTypeInitializer<BKTraits, TraitObject>.Instance.Diligent);
            __instance.HelgeredKara.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookHelgeredKara, new TextObject("An action story, full of battle. The shieldmaiden Kara chooses the warrior Helgered as her lover, as he is the only man who can defeat her in combat. Her father, who pledged her to another, comes with his sons and his huscarls to kill Helgered. They fight, and Helgered and Kars slaughter the entire host except for Kara's beloved younger -- who, alas, growing up to avenge his father by slaying Helgered. “A light pierced the gloom over Northern cliffs...”", null), ROTLanguages.Instance.OldTongue, BookUse.Skillbook, DefaultSkills.OneHanded, DefaultTraits.Valor);
            __instance.KaisLayala.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookKaisLayala, new TextObject("A sad story that reminds many of their powerlesness towards the ways of the world. The shepherd boy Kais and the nobleman's daughter Layala love each other, but they can never marry. The poem is Kais's lament as he wanders alone, unwilling to forget his true love, driving himself mad with longing. “The wind that blows the dry steppe dust...”", null), ROTLanguages.Instance.Ghiscari, BookUse.Skillbook, DefaultSkills.Charm, DefaultTypeInitializer<BKTraits, TraitObject>.Instance.Humble);
            __instance.LoveCastle.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookLoveCastle, new TextObject("An allegoric Westerosi tale. It describes how a brave but rough warrior wins the heart of his lady by learning the virtues of chivalry, becoming a true and noble knight.", null), ROTLanguages.Instance.Westerosi, BookUse.Skillbook, BKSkills.Instance.Lordship, DefaultTraits.Honor);
            AccessTools.Property(typeof(DefaultBookTypes), "HeatsDesire").SetValue(__instance, new BookType("book_heartsDesire"));
            __instance.HeatsDesire.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookHeartsDesire, new TextObject("A Lyseni tale of love that can be interpreted either erotically or spiritually. The lover realizes the majesty of the divine by gazing upon the body of his beloved. The appeal to love through the naked body is offensive to the highly moralistic, yet compelling to those of more relaxed morals. “You are the first and the last...”", null), ROTLanguages.Instance.LowValyrian, BookUse.Skillbook, DefaultSkills.Charm, DefaultTypeInitializer<BKTraits, TraitObject>.Instance.Seductive);
            AccessTools.Property(typeof(DefaultBookTypes), "Siege").SetValue(__instance, new BookType("book_siege"));
            __instance.Siege.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookSiege, new TextObject("A Yi Tish, illustrated treatise on siege warfare, also known as poliorcetics. The manuscript goes over all the main topics of sieges: building appropriate engines, bringing men upon the enemy's walls, as well as keeping the enemy off yours. All those in Essos can attest that none can match the peoples of Yi Ti in terms of siege warfare.", null), ROTLanguages.Instance.YiTish, BookUse.Focusbook, DefaultSkills.Engineering, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Strategikon").SetValue(__instance, new BookType("book_tactics"));
            __instance.Strategikon.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookStrategikon, new TextObject("Assembled for use by the Targaryen dynasty, Strategikon compiles series of treatises on army maneuvers and tatics. The book deals with diverse formations and battle tactics used by opponents of the Seven Kingdoms, since it's inception by Aegon the Conqueror. The book is treated as basic education for military-minded lords in the Seven Kingdoms.", null), ROTLanguages.Instance.Westerosi, BookUse.Focusbook, DefaultSkills.Tactics, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Trade").SetValue(__instance, new BookType("book_trade"));
            __instance.Trade.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookTrade, new TextObject("Written by Lo Doq of the Yi Ti, the treatise compiles a series of reflections on trade routes and trading practices the caravaneer deal with in his lifetime. From the Jogos Nhai nomadic traders, through the Qartheen bureaucrats up to the sea-faring traders of Ib, Lo Doq writes on his experience of mastering the trade through decades of field experience.", null), ROTLanguages.Instance.YiTish, BookUse.Focusbook, DefaultSkills.Trade, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Dictionary").SetValue(__instance, new BookType("book_dictionary"));
            __instance.Dictionary.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookDictionary, new TextObject("Dictionarium Valyrium is a compendium of basic words and syntax of the languages in Essos. Used to further the former Freehold's influence on different cultures, it serves any language by comparing it to High Valyrian.", null), ROTLanguages.Instance.HighValyrian, BookUse.Dictionary, null, null);
            __instance.GreenKnight.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookGreenKnight, new TextObject("A Westerosi tale that explores the themes of chivalry, honor and sacrifice. A knight is made an offer by this mysterious, green knight figure, at the possible cost of his life. Believing the danger to be absurd and the offer purely benefitial to himself, he makes a pledge. A year later, the terms of the offer come due, and the knight's honor and integrity are challenged: will he keep his word and risk his life?", null), ROTLanguages.Instance.Westerosi, BookUse.Skillbook, DefaultSkills.Riding, DefaultTraits.Honor);
            AccessTools.Property(typeof(DefaultBookTypes), "Mounted").SetValue(__instance, new BookType("book_riding"));
            __instance.Mounted.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookArtHorsemanship, new TextObject("An ancient Dothraki treatise concerning the training, care and art of mounting horses. The treatise is the staple manuscript on the long Dothraki equestrian tradition, an art developed by its Khals and culminated into the unstoppable force of the Khalasar.", null), ROTLanguages.Instance.Dothraki, BookUse.Focusbook, DefaultSkills.Riding, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Leadership").SetValue(__instance, new BookType("book_leadership"));
            __instance.Leadership.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookLeadership, new TextObject("An ancient and, somewhat heretical, Ghiscari manual on how to lead and inspire owned slaves rather than simple punishment.", null), ROTLanguages.Instance.Ghiscari, BookUse.Focusbook, DefaultSkills.Leadership, null);
            AccessTools.Property(typeof(DefaultBookTypes), "OneHanded").SetValue(__instance, new BookType("book_oneHanded"));
            __instance.OneHanded.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookOneHanded, new TextObject("\"Water Dancing Ms. I.33\" is the earliest known Braavosi combat manual. The text provides guidance on the use of a single-handed swords. The fencing system is based on number of wards which are answered by defensive postures for each one of them. The treatise expound a martial system of defensive and offensive techniques between a master and a pupil, each armed with a sword and a shield, drawn in ink and watercolour and accompanied with text in Low Valyrian, interspersed by Braavosi fencing terms. ", null), ROTLanguages.Instance.LowValyrian, BookUse.Focusbook, DefaultSkills.OneHanded, null);
            AccessTools.Property(typeof(DefaultBookTypes), "TwoHanded").SetValue(__instance, new BookType("book_twoHanded"));
            __instance.TwoHanded.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookTwoHanded, new TextObject("The book presents the legend of Huzhor Amai, mythical ruler of Sarnor, who went on a pilgrimage around Sarnath to seek aid from the spirits to improve the Tall Men army. He met Josimakazma, who gifted him the Sunblade, the first two handed sword in Sarnor. Soon after, Huzhor Amai had found many smithies in his domain, that supplied Sarnori archers with two hand swords, creating an army of Tall Men Champions and became the first king of the river Sarne. Tall Men Champions were a nightmare for the Valyrian and Ghiscari empires for centuries, not only because of their very well known archery skills, but also because of exceptional swordmanship.", null), ROTLanguages.Instance.Sarnori, BookUse.Focusbook, DefaultSkills.TwoHanded, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Crossbow").SetValue(__instance, new BookType("book_crossbow"));
            __instance.Crossbow.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookCrossbow, new TextObject("Written by an engineer of Myr, this monumental work is considered a founding text of Myr, as it popularized usage of crossbows and siege engines among Myrish lords during the rule of the Triarchy. Thanks to clear descriptions of crossbow and balista constuction and simple explanations of physics behind the contraption even lords of a single village were able to supply their peasants with deadly weapons. It is said that Myr is built on crossbow and lance and this work is a proof that the engineers of Myr deserve their status as the most advanced of the Free Cities.", null), ROTLanguages.Instance.LowValyrian, BookUse.Focusbook, DefaultSkills.Crossbow, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Bow").SetValue(__instance, new BookType("book_bow"));
            __instance.Bow.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookBow, new TextObject("The History of Westerosi Archery is a monography of most popular weapon around the continent: bows and arrows. Written by a renowned archer, Symeon Star-Eyes, the book describes the variety of bows and arrows used across the continent, along with the description of culture favorite variants. Each Westerosi culture's archery traditions and practical ways to use those in warfare is described in separate chapters. The author also introduces most of bow constructions invented in Westeros, from the simplest mountain bows to rather expensive and complicated longbows used by the nobility.", null), ROTLanguages.Instance.Westerosi, BookUse.Focusbook, DefaultSkills.Bow, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Polearm").SetValue(__instance, new BookType("book_polearm"));
            __instance.Polearm.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookPolearm, new TextObject("Volantene debate of 1074 is a record of events that occurred during a tournament of Volantis in a local inn. A group of Khal's Guards, entourage of young Dothraki Bloodrider Monchug (who came to Volantis to take part in the tournament) had gotten into discussion with Pentoshi voulgiers serving in the local garrison about whose swingeable polearm armament was better. Soon the present Cataphracts of the same garrison joined the discussion, with intention to prove that long, thrustable lances are superior. The debate resulted in 12 deaths, 23 injured and maimed and, as declared unanimously by witnesses, was won by Gareth, a local peasant, who was passing by the inn and entered carrying his trusty rake, to see what all the ruckus is about.", null), ROTLanguages.Instance.LowValyrian, BookUse.Focusbook, DefaultSkills.Polearm, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Throwing").SetValue(__instance, new BookType("book_throwing"));
            __instance.Throwing.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookThrowing, new TextObject("An ancient Ghiscari treatise on the art of the throwing spear\r\n\r\nThis slender but revered volume, composed in High Ghiscari and bound in cracked harpy-hide, is attributed to Mazrek son of Torgas, a slave-general who rose to brief prominence during the Third Ghiscari Empire. The work details forty-two forms for the casting of spears, each named after beasts sacred to Old Ghis: the Crocodile’s Lunge, the Vulture’s Drop, the Bull’s Fury, and so forth. The text is both martial manual and moral guide, for Mazrek instructs that a warrior’s worth lies not only in the strength of his arm, but in the discipline of his cast. Each form is accompanied by aphorisms extolling obedience, hierarchy, and the submission of lesser peoples to the “natural dominion” of the Ghiscari.", null), ROTLanguages.Instance.Ghiscari, BookUse.Focusbook, DefaultSkills.Throwing, null);
            AccessTools.Property(typeof(DefaultBookTypes), "Medicine").SetValue(__instance, new BookType("book_medicine"));
            __instance.Medicine.Initialize(DefaultTypeInitializer<BKItems, ItemObject>.Instance.BookMedicine, new TextObject("Valyrian Papyrus is probably the oldest known medical text in Essos. The book is written as dialogue between a Valyrian Dragonlord and his physician in which the ruler asks questions and the physician provides the answers. This type of discourse makes possible both a discussion of general ethics and philosophies of life and the inclusion of the prevailing Valyrian religious beliefs. In general, the book integrates moral and physical conduct and provides an important relationship between mental and physical states of health. The common theme seems to be moderation in everything, harmony with nature, contentment with oneself, and restraining and reducing one's desires- sensible ways of handling physical and mental stresses and their devastating effects on health and longevity.", null), ROTLanguages.Instance.HighValyrian, BookUse.Focusbook, DefaultSkills.Medicine, null);
            return false;
        }
    }
}
